# Generated by Django 5.1.4 on 2025-02-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_options_remove_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
    ]
